require('./barchart-tests');
require('./linechart-tests');
require('./areachart-tests');
require('./piechart-tests');
require('./treemapchart-tests');
require('./scatterchart-tests');
require('./legend-tests');
require('./voronoi-tests');
require('./utils-tests');
